In [6]:
from tokeniser import Tokeniser
from datasets import load_dataset
import numpy as np

In [ ]:
dataset = load_dataset("wikitext", "wikitext-103-v1")

train_text = dataset['train']['text']
validate_text = dataset['validation']['text']
test_text = dataset['test']['text']

loaded wikitext dataset


In [2]:
tokeniser = Tokeniser()
tokeniser.fit_vocab(train_text)

fit tokeniser


In [10]:
train_tokens = tokeniser.tokenise(train_text)

In [ ]:
def build_context_windows(tokens):
    pass

print(np.lib.stride_tricks.sliding_window_view(train_tokens, 4)[:10])

[[178738  48996 190971 172677]
 [ 48996 190971 172677 178738]
 [190971 172677 178738 228432]
 [172677 178738 228432 137977]
 [178738 228432 137977  48996]
 [228432 137977  48996 214793]
 [137977  48996 214793  32451]
 [ 48996 214793  32451  95878]
 [214793  32451  95878 190971]
 [ 32451  95878 190971  47282]]
